name: Docker Scout Scan

on:
  workflow_dispatch:

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull ghcr.io/evdokiafrd/hw0_security_evdokia_foradi_part_2:latest

      - name: Run Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ghcr.io/evdokiafrd/hw0_security_evdokia_foradi_part_2:latest
          exit-code: false
