name: SBOM/SCA Scan

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'The Docker image to scan'
        required: true
        default: 'ghcr.io/evdokiafrd/hw0_security_evdokia_foradi_part_2:latest'

jobs:
  scout:
    runs-on: ubuntu-latest

    steps:
      - name: Pull the image
        run: docker pull ${{ github.event.inputs.docker_image }}

      - name: Install Docker Scout CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh

      - name: Run scan and save output
        run: |
          docker scout cves ${{ github.event.inputs.docker_image }} > scout_report.txt || true

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: scout-report
          path: scout_report.txt
